# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Freevite"
  port = 8910
  apiUrl = "${API_URL:/.netlify/functions}"
  includeEnvironmentVariables = [
    'SITE_HOST',

    'SENTRY_DSN',

    # Netlify: https://docs.netlify.com/configure-builds/environment-variables
    'CONTEXT',
    'DEPLOY_PRIME_URL',

    # Email
    'FROM_EMAIL',
    'SMTP_HOST',
    'SMTP_PORT',
    'SMTP_USER',
    'SMTP_PASS',

    # S3
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY',
    'AWS_DEFAULT_REGION',
    'S3_BUCKET',
    'S3_NAMESPACE',
  ]
[api]
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
