name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ci_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - run: yarn install --immutable
      # - run: yarn rw prisma generate
      - run: env > .env # HACK to get DATABASE_URL into Prisma
      # - run: yarn rw type-check
      - run: yarn rw test --watch=false
        env:
          DATABASE_URL: postgresql://username:password@localhost:5432/ci_test
      # - run: yarn rw lint
