name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - run: yarn install --immutable
      - run: env
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/ci_test
      - run: yarn jest
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/ci_test
